import React from 'react';
import { View, Text, ScrollView, TouchableOpacity, Platform, StatusBar } from 'react-native';
import { useRouter } from 'expo-router';
import { SOL_THEME } from '../constants/theme';

export default function PrivacyScreen() {
  const router = useRouter();

  return (
    <View style={{ flex: 1, backgroundColor: SOL_THEME.background }}>
      <StatusBar barStyle="light-content" />
      {/* Header */}
      <View style={{
        paddingTop: Platform.OS === 'ios' ? 56 : 44,
        paddingHorizontal: 20,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: SOL_THEME.border,
        backgroundColor: SOL_THEME.surface,
        flexDirection: 'row',
        alignItems: 'center',
      }}>
        <TouchableOpacity onPress={() => router.back()} style={{ marginRight: 16, padding: 4 }}>
          <Text style={{ color: SOL_THEME.primary, fontSize: 22 }}>←</Text>
        </TouchableOpacity>
        <View>
          <Text style={{ color: SOL_THEME.text, fontSize: 16, fontWeight: '700' }}>Privacy Policy</Text>
          <Text style={{ color: SOL_THEME.textMuted, fontSize: 11, marginTop: 1 }}>Sovereign Sol · Lycheetah</Text>
        </View>
      </View>

      <ScrollView
        style={{ flex: 1 }}
        contentContainerStyle={{ padding: 20, paddingBottom: 60 }}
        showsVerticalScrollIndicator={false}
      >
        <Section label="LAST UPDATED">
          <Body>June 2026. This policy reflects exactly what the app does — no more, no less.</Body>
        </Section>

        <Section label="THE SHORT VERSION">
          <Body>Your data stays on your device. We do not sell it, broker it, or share it with advertisers. We collect minimal anonymous analytics to understand how the app is used. You can turn that off in Settings.</Body>
        </Section>

        <Section label="WHAT WE COLLECT">
          <SubHead>Anonymous usage analytics (Aptabase)</SubHead>
          <Body>App opens, feature interactions, and session counts — no names, no email, no content, no personal data. Session IDs are ephemeral and not linked across sessions. You can opt out in Settings → Privacy.</Body>
          <SubHead>Device identifier</SubHead>
          <Body>A random string generated by the app (format: sol-[timestamp]-[random]). This is NOT your hardware ID, advertising ID, or any system identifier. It exists only to deduplicate analytics counts.</Body>
          <SubHead>Birth data (if you use Zodiac)</SubHead>
          <Body>Birth date, time, and location — stored locally in AsyncStorage on your device only. This data leaves your device only when you explicitly request a natal chart or transit reading, and only to the AI provider processing that reading.</Body>
          <SubHead>Your mother's name (Zodiac)</SubHead>
          <Body>Stored locally only. Never transmitted except when included in a reading you explicitly request.</Body>
          <SubHead>Journal entries and personal notes</SubHead>
          <Body>Stored locally on your device. Never transmitted to our servers.</Body>
        </Section>

        <Section label="AI PROVIDERS">
          <Body>Sovereign Sol connects to these AI providers to power responses and readings. When you send a message or request a reading, your input is sent to the provider handling that request:</Body>
          <Body>· Google Gemini{'\n'}· OpenAI{'\n'}· Anthropic{'\n'}· DeepSeek{'\n'}· Moonshot / Kimi{'\n'}· NVIDIA</Body>
          <Body>Each provider has their own privacy policy and data handling practices. We recommend reviewing the policy of the provider you use most.</Body>
          <Body>Your AI keys (if you supply your own) are stored in AsyncStorage on your device. We do not have a backend that receives or stores your keys.</Body>
        </Section>

        <Section label="LOCAL STORAGE">
          <Body>Sovereign Sol uses AsyncStorage to store your data locally on your device. This storage is not separately encrypted beyond what your device's operating system provides. We do not use iOS Keychain or Android Keystore for this data — we are being candid about that trade-off.</Body>
          <Body>Data stored locally includes: your name, companion state, journal entries, birth data, AI key preferences, theme settings, and dive history.</Body>
        </Section>

        <Section label="WHAT WE DO NOT DO">
          <Body>· We do not sell your data{'\n'}· We do not share your data with advertisers{'\n'}· We do not build advertising profiles{'\n'}· We do not track you across other apps or websites{'\n'}· We do not collect your precise location (birth location for Zodiac is entered manually){'\n'}· We do not collect push notification tokens</Body>
        </Section>

        <Section label="THE COVENANT">
          <Body>The intelligence in Sovereign Sol is never gated by payment. Free users get the same quality of response as paid subscribers. We will never make the free experience worse to push you toward a subscription. This is a founding principle, not a policy that changes.</Body>
        </Section>

        <Section label="AGE REQUIREMENT">
          <Body>Sovereign Sol is intended for users 16 and older. By using this app you confirm you meet this requirement.</Body>
        </Section>

        <Section label="CONTACT">
          <Body>Questions about this policy or your data:{'\n'}lycheetahsol@gmail.com</Body>
        </Section>

        <View style={{ marginTop: 32, paddingTop: 20, borderTopWidth: 1, borderTopColor: SOL_THEME.border }}>
          <Text style={{ color: SOL_THEME.textMuted, fontSize: 10, textAlign: 'center', letterSpacing: 1, fontFamily: Platform.OS === 'ios' ? 'Courier New' : 'monospace' }}>
            ⊚ SOVEREIGN SOL · LYCHEETAH · IN VERITAS
          </Text>
        </View>
      </ScrollView>
    </View>
  );
}

function Section({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <View style={{ marginBottom: 24 }}>
      <Text style={{
        color: SOL_THEME.textMuted, fontSize: 10, fontWeight: '700',
        letterSpacing: 2, fontFamily: Platform.OS === 'ios' ? 'Courier New' : 'monospace',
        marginBottom: 10,
      }}>◉ {label}</Text>
      {children}
    </View>
  );
}

function SubHead({ children }: { children: string }) {
  return (
    <Text style={{ color: SOL_THEME.text, fontSize: 13, fontWeight: '600', marginBottom: 4, marginTop: 10 }}>
      {children}
    </Text>
  );
}

function Body({ children }: { children: React.ReactNode }) {
  return (
    <Text style={{ color: SOL_THEME.textMuted, fontSize: 13, lineHeight: 20, marginBottom: 6 }}>
      {children}
    </Text>
  );
}
