export type SubjectLayer = 'FOUNDATION' | 'MIDDLE' | 'EDGE';

export type Subject = {
  name: string;
  domain: string;
  layer: SubjectLayer;
  description: string;
  traditions?: string[];
};

export type SubjectDomain = {
  id: string;
  label: string;
  glyph: string;
  color: string;
  description: string;
  subjects: Subject[];
};

export const MYSTERY_SCHOOL_DOMAINS: SubjectDomain[] = [
  {
    id: 'meditation',
    label: 'Meditation & Contemplative',
    glyph: '◯',
    color: '#4A9EFF',
    description: 'The practices of stillness, insight, and presence across traditions.',
    subjects: [
      { name: 'Shamatha — Calm Abiding', domain: 'Meditation & Contemplative', layer: 'FOUNDATION', description: 'The foundation of all contemplative practice. Learning to rest the mind without forcing it. The ground before insight.' },
      { name: 'Vipassana — Insight Meditation', domain: 'Meditation & Contemplative', layer: 'FOUNDATION', description: 'Direct observation of arising and passing phenomena. Seeing things as they are, not as you want them to be.' },
      { name: 'Loving-Kindness — Metta', domain: 'Meditation & Contemplative', layer: 'FOUNDATION', description: 'Systematic cultivation of warmth — toward self, toward others, toward all beings. The heart as a muscle.' },
      { name: 'Body Scan — Mindfulness-Based Awareness', domain: 'Meditation & Contemplative', layer: 'FOUNDATION', description: 'Systematic attention to each region of the body. The fastest way to learn that awareness can be directed.' },
      { name: 'Non-Sleep Deep Rest — NSDR / Yoga Nidra', domain: 'Meditation & Contemplative', layer: 'MIDDLE', description: 'Deliberate entry into hypnagogic states for restoration and reprogramming. The body sleeps; awareness watches.' },
      { name: 'Tantric Visualization — Deity Practice', domain: 'Meditation & Contemplative', layer: 'MIDDLE', description: 'Constructing a mental body with precision and detail. What visualization actually requires neurologically.' },
      { name: 'Open Awareness — Rigpa Foundation', domain: 'Meditation & Contemplative', layer: 'MIDDLE', description: 'Resting in the space in which experiences arise, rather than the experiences themselves.' },
      { name: 'Samatha-Vipassana — The Two Wings', domain: 'Meditation & Contemplative', layer: 'MIDDLE', description: 'The complete path requires both calm and insight working together. What happens when they integrate.' },
      { name: 'Choiceless Awareness — J. Krishnamurti', domain: 'Meditation & Contemplative', layer: 'MIDDLE', description: 'Attention without an observer. The radical claim that the meditator is the problem — not the solution.' },
      { name: 'Zen Koan Work', domain: 'Meditation & Contemplative', layer: 'EDGE', description: 'Questions designed to break the reasoning mind. Not puzzles to solve — thresholds to pass through. Sanity is not the goal.' },
      { name: 'Dzogchen — Natural Mind', domain: 'Meditation & Contemplative', layer: 'EDGE', description: 'The Tibetan pointing-out instruction. Recognition of awareness as it already is. This cannot be practiced — only recognised.' },
      { name: 'Mahamudra — The Great Seal', domain: 'Meditation & Contemplative', layer: 'EDGE', description: 'The Kagyu direct path. Mind looking at mind. What the mind finds when it turns on itself completely.' },
      { name: 'Hesychasm — The Prayer of the Heart', domain: 'Meditation & Contemplative', layer: 'EDGE', description: 'Eastern Orthodox inner prayer. The Jesus Prayer repeated until it descends from the mind into the heart. Theosis through stillness. One of the world\'s most rigorous contemplative systems — rarely studied outside the Orthodox tradition.' },
      { name: 'The Witness — Who is Watching?', domain: 'Meditation & Contemplative', layer: 'MIDDLE', description: 'The meta-awareness that observes thoughts without being them. Identified across traditions as the foundation of practice. What it is, how it is found, and what changes when you rest there.' },
    ],
  },
  {
    id: 'somatic',
    label: 'Somatic & Body',
    glyph: '⟁',
    color: '#E74C3C',
    description: 'The body as the site of knowing. What the nervous system holds.',
    subjects: [
      { name: 'Somatic Experiencing — Trauma Releasing', domain: 'Somatic & Body', layer: 'FOUNDATION', description: 'Peter Levine\'s protocol for completing interrupted survival responses stored in the body.' },
      { name: 'Pranayama — Classical Breathwork', domain: 'Somatic & Body', layer: 'FOUNDATION', description: 'The science of breath as a lever on the autonomic nervous system.' },
      { name: 'Polyvagal Theory — Applied', domain: 'Somatic & Body', layer: 'FOUNDATION', description: 'Stephen Porges\' map of the autonomic nervous system. Why safety is biological before it is psychological.' },
      { name: 'Qigong / Tai Chi', domain: 'Somatic & Body', layer: 'MIDDLE', description: 'Movement as meditation. Energy cultivation through form and flow.' },
      { name: 'Authentic Movement', domain: 'Somatic & Body', layer: 'MIDDLE', description: 'Moving from inner impulse with a witness present. The body knows before the mind does.' },
      { name: 'Sensorimotor Psychotherapy', domain: 'Somatic & Body', layer: 'MIDDLE', description: 'Pat Ogden\'s integration of body-based processing with talk therapy. Where trauma lives in posture and gesture.' },
      { name: 'Wim Hof Method — Cold and Breath', domain: 'Somatic & Body', layer: 'MIDDLE', description: 'Deliberate stress as a path to autonomic mastery. The evidence for voluntary control of the immune system.' },
      { name: 'Continuum Movement', domain: 'Somatic & Body', layer: 'MIDDLE', description: 'Emilie Conrad\'s method. The body as fluid intelligence in conversation with gravity. Slow is not slow.' },
      { name: 'Holotropic Breathwork', domain: 'Somatic & Body', layer: 'EDGE', description: 'Stanislav Grof\'s method for accessing non-ordinary states through breath alone. What surfaces cannot be predicted.' },
      { name: 'Bioenergetics — Reich and Lowen', domain: 'Somatic & Body', layer: 'EDGE', description: 'Wilhelm Reich\'s discovery of character armour — the body as frozen biography. What releasing it costs and what it frees.' },
      { name: 'Feldenkrais Method — Awareness Through Movement', domain: 'Somatic & Body', layer: 'MIDDLE', description: 'Moshe Feldenkrais\' discovery: improve the image, not the action. The nervous system learns through difference, not repetition. What happens when you stop trying and start sensing.' },
      { name: 'Alexander Technique — The Use of the Self', domain: 'Somatic & Body', layer: 'MIDDLE', description: 'F.M. Alexander\'s radical insight: most human suffering is self-inflicted through unconscious muscular habit. Inhibition — the pause before reaction — as the foundational skill.' },
    ],
  },
  {
    id: 'shadow',
    label: 'Shadow & Depth Psychology',
    glyph: '◐',
    color: '#9B59B6',
    description: 'What lives below the threshold. Jung, IFS, and the integration of the rejected self.',
    subjects: [
      { name: 'Jungian Shadow Work', domain: 'Shadow & Depth Psychology', layer: 'FOUNDATION', description: 'Identifying and integrating the parts of yourself you were taught to reject or hide.' },
      { name: 'Dream Work — Amplification Method', domain: 'Shadow & Depth Psychology', layer: 'FOUNDATION', description: 'Using the Jungian method to expand dream images into their full symbolic meaning. The unconscious speaks in metaphor.' },
      { name: 'The Persona — The Social Mask', domain: 'Shadow & Depth Psychology', layer: 'FOUNDATION', description: 'The constructed self we present to the world. What it costs to wear it. What it hides.' },
      { name: 'Active Imagination', domain: 'Shadow & Depth Psychology', layer: 'MIDDLE', description: 'Jung\'s method of dialogue with unconscious figures. The inner world has characters — and they have something to say.' },
      { name: 'Inner Child Work — IFS Protocol', domain: 'Shadow & Depth Psychology', layer: 'MIDDLE', description: 'Richard Schwartz\'s Internal Family Systems. The mind as a system of parts, each with a role.' },
      { name: 'Voice Dialogue — Hal and Sidra Stone', domain: 'Shadow & Depth Psychology', layer: 'MIDDLE', description: 'Giving direct voice to disowned sub-personalities. What happens when you stop speaking for them.' },
      { name: 'Complexes — Autonomous Psychic Structures', domain: 'Shadow & Depth Psychology', layer: 'MIDDLE', description: 'Jung\'s discovery that the psyche contains semi-independent units of energy that can temporarily take over. What triggers yours.' },
      { name: 'Anima and Animus — The Contrasexual Soul', domain: 'Shadow & Depth Psychology', layer: 'MIDDLE', description: 'The inner feminine in a man, the inner masculine in a woman. How they project onto partners and how to reclaim them.' },
      { name: 'Individuation — The Life\'s Work', domain: 'Shadow & Depth Psychology', layer: 'MIDDLE', description: 'Jung\'s term for the full journey toward wholeness. Not happiness. Not enlightenment. The complete expression of who you actually are.' },
      { name: 'Projective Identification — Working with What You Attract', domain: 'Shadow & Depth Psychology', layer: 'EDGE', description: 'The deepest Jungian mechanism — how the unconscious outsources its contents to others. What your reactions are really about.' },
      { name: 'The Wounded Healer Archetype', domain: 'Shadow & Depth Psychology', layer: 'EDGE', description: 'Chiron as a map for those whose gift emerges directly from their wound. How to metabolise rather than perform.' },
      { name: 'Archetypal Psychology — James Hillman', domain: 'Shadow & Depth Psychology', layer: 'EDGE', description: 'Hillman\'s radical departure from ego psychology. The psyche is multiple, not unified. Pathology as perspective, not error. "Re-visioning" psychology from a soul-centred view.' },
      { name: 'Mimetic Theory — René Girard', domain: 'Shadow & Depth Psychology', layer: 'EDGE', description: 'We desire what others desire. Girard\'s anthropological discovery: desire is imitated, not spontaneous. Scapegoating as the hidden mechanism of social order. The implications for understanding conflict, envy, and identity.' },
    ],
  },
  {
    id: 'alchemy',
    label: 'Alchemical & Hermetic Arts',
    glyph: '⊚',
    color: '#F5A623',
    description: 'Transformation as both outer chemistry and inner work. Solve et Coagula.',
    subjects: [
      { name: 'Chrysopoeia — Transformation Calculus', domain: 'Alchemical & Hermetic Arts', layer: 'FOUNDATION', description: 'The Lycheetah formalisation of alchemical transformation. How matter — and mind — changes state.' },
      { name: 'Nigredo, Albedo, Citrinitas, Rubedo', domain: 'Alchemical & Hermetic Arts', layer: 'FOUNDATION', description: 'The four stages of the Great Work. How they appear in psychological development and creative process.' },
      { name: 'The Seven Operations — Full Sequence', domain: 'Alchemical & Hermetic Arts', layer: 'FOUNDATION', description: 'Calcination, Dissolution, Separation, Conjunction, Fermentation, Distillation, Coagulation. The complete inner laboratory.' },
      { name: 'Classical Alchemy — Practical Spagyrics', domain: 'Alchemical & Hermetic Arts', layer: 'MIDDLE', description: 'Working with plant materials using alchemical principles. The laboratory as a practice.' },
      { name: 'Hermetic Kabbalah — Tree of Life Navigation', domain: 'Alchemical & Hermetic Arts', layer: 'MIDDLE', description: 'The Sephiroth as a map of consciousness and a framework for understanding emanation.' },
      { name: 'Paracelsian Medicine — Archeus and Vital Force', domain: 'Alchemical & Hermetic Arts', layer: 'MIDDLE', description: 'Paracelsus\' integration of alchemy with healing. The vital force that precedes chemical composition.' },
      { name: 'Sol et Luna — The Sacred Marriage', domain: 'Alchemical & Hermetic Arts', layer: 'MIDDLE', description: 'The Conjunction of opposites: solar and lunar, fixed and volatile, conscious and unconscious. The Rebis as goal.' },
      { name: 'The Philosopher\'s Stone — What It Actually Is', domain: 'Alchemical & Hermetic Arts', layer: 'MIDDLE', description: 'Not a literal stone. The culmination of the Work. What the alchemists meant and what it means to produce it in yourself.' },
      { name: 'Antimony — The Philosophical Wolf', domain: 'Alchemical & Hermetic Arts', layer: 'EDGE', description: 'The most paradoxical alchemical substance. Both poison and purifier. What it means to work with ambivalence directly.' },
      { name: 'The Emerald Tablet — Close Reading', domain: 'Alchemical & Hermetic Arts', layer: 'EDGE', description: 'Thirteen sentences that contain a complete cosmology. What "As above, so below" actually means when taken seriously.' },
      { name: 'Fermentation — Death Before the Gold', domain: 'Alchemical & Hermetic Arts', layer: 'EDGE', description: 'The fifth operation. The grain must rot before wine can rise. What dies in you before the gold appears — and why you cannot skip this stage.' },
      { name: 'John Dee & Enochian — The Angelic Language', domain: 'Alchemical & Hermetic Arts', layer: 'EDGE', description: 'Elizabeth I\'s court magician. The received angelic alphabet. What Dee and Kelley actually did in their scrying sessions — and what the modern occult tradition made of it. Rigour applied to the impossible.' },
      { name: 'The Green Lion — Vitriol and the First Matter', domain: 'Alchemical & Hermetic Arts', layer: 'EDGE', description: 'The viriditas — the Green Lion that devours the sun. The first matter of the Work: the corrosive force that must be tamed before the gold can be produced. What it represents in the psychological laboratory.' },
    ],
  },
  {
    id: 'divination',
    label: 'Divination Arts',
    glyph: '✦',
    color: '#1ABC9C',
    description: 'Pattern-reading as a contemplative practice. Not prediction — attention.',
    subjects: [
      { name: 'Bibliomancy — Sacred Text as Oracle', domain: 'Divination Arts', layer: 'FOUNDATION', description: 'Opening a text at random and reading it as a response. Why this works even without metaphysical commitments.' },
      { name: 'Numerology — Gematria and Isopsephy', domain: 'Divination Arts', layer: 'FOUNDATION', description: 'The Hebrew and Greek systems of letter-number correspondence. How meaning and number were once the same thing.' },
      { name: 'Runes — Elder Futhark as Cosmological Map', domain: 'Divination Arts', layer: 'FOUNDATION', description: 'The 24 staves as a complete Norse cosmology, not just a fortune-telling tool. Each rune is a force, not a symbol.' },
      { name: 'Tarot — Major Arcana Journey', domain: 'Divination Arts', layer: 'MIDDLE', description: 'The 22 archetypes as a map of the soul\'s journey. The cards as a mirror, not an oracle.' },
      { name: 'I Ching — Change Work', domain: 'Divination Arts', layer: 'MIDDLE', description: 'Three thousand years of pattern wisdom. The Book of Changes as a philosophy of transition.' },
      { name: 'Tarot — Minor Arcana and the Elements', domain: 'Divination Arts', layer: 'MIDDLE', description: 'The 56 cards as a map of practical life. How the four suits encode the four elements as modes of experience.' },
      { name: 'Ogham — Celtic Tree Wisdom', domain: 'Divination Arts', layer: 'MIDDLE', description: 'The ancient Irish alphabet as a sacred system. Each letter is a tree, a sound, a wisdom principle, a season.' },
      { name: 'Astrology — Natal Chart Study', domain: 'Divination Arts', layer: 'EDGE', description: 'The birth chart as a map of potential and tendency. What the sky said when you arrived.' },
      { name: 'Geomancy — Earth Reading', domain: 'Divination Arts', layer: 'EDGE', description: 'The oldest formal divination system. Sixteen figures generated from earth, read as pattern.' },
      { name: 'Scrying — Mirror, Water, and Flame', domain: 'Divination Arts', layer: 'EDGE', description: 'Using reflective or luminous surfaces to alter awareness and receive imagery. The neuroscience of why it works.' },
      { name: 'Dream Incubation — Sleeping as Practice', domain: 'Divination Arts', layer: 'MIDDLE', description: 'The ancient Greek and Egyptian practice of sleeping in a sacred space to receive oracular dreams. Asklepion healing through the dream. How to invite the unconscious with intention.' },
      { name: 'Chiromancy — Reading the Hand', domain: 'Divination Arts', layer: 'FOUNDATION', description: 'The oldest divination system still widely practised. Not fortune-telling — a map of tendency and character. What the lines, mounts, and proportions actually indicate — and the psychology beneath the symbols.' },
    ],
  },
  {
    id: 'shamanic',
    label: 'Shamanic Arts',
    glyph: '⋈',
    color: '#27AE60',
    description: 'The oldest technology for navigating between worlds. Indigenous wisdom and modern protocols.',
    subjects: [
      { name: 'Vision Quest — Modern Protocol', domain: 'Shamanic Arts', layer: 'FOUNDATION', description: 'Alone in nature, without distractions, until something real happens. The original initiatory structure.' },
      { name: 'Power Animal Retrieval', domain: 'Shamanic Arts', layer: 'FOUNDATION', description: 'The shamanic concept of animal helpers as aspects of one\'s own nature. The journey to meet them.' },
      { name: 'The Shamanic Drum — The Heartbeat', domain: 'Shamanic Arts', layer: 'FOUNDATION', description: 'Why monotonous drumming at 4-7 Hz induces trance. The oldest technology for changing consciousness is a stretched skin.' },
      { name: 'Core Shamanism — Journeying', domain: 'Shamanic Arts', layer: 'MIDDLE', description: 'Michael Harner\'s cross-cultural extraction of the shamanic journey technique. Lower, middle, upper worlds.' },
      { name: 'Plant Communion — Non-Pharmacological', domain: 'Shamanic Arts', layer: 'MIDDLE', description: 'Relationship with plant consciousness through proximity, attention, and silence. No ingestion required.' },
      { name: 'Ancestral Healing — Lineage Work', domain: 'Shamanic Arts', layer: 'MIDDLE', description: 'The wounds and gifts that move through family lines. Practical protocols for what cannot be fixed by talking.' },
      { name: 'Trance States — Entering and Working', domain: 'Shamanic Arts', layer: 'MIDDLE', description: 'The phenomenology of shamanic altered states. How to enter, navigate, and return with useful information.' },
      { name: 'Soul Retrieval — The Fragmentation Model', domain: 'Shamanic Arts', layer: 'EDGE', description: 'The shamanic explanation for dissociation. Parts of the self that left during overwhelm and can be called back.' },
      { name: 'Extraction — Spiritual First Aid', domain: 'Shamanic Arts', layer: 'EDGE', description: 'Working with intrusive energies using shamanic methods. Requires strong foundation, clean boundaries, and earned authority.' },
      { name: 'Death Walking — The Psychopomp Role', domain: 'Shamanic Arts', layer: 'EDGE', description: 'The shaman as guide for the dying and the dead. What it means to cross someone over — and what it costs the walker.' },
      { name: 'Plant Dietas — Learning from Plant Teachers', domain: 'Shamanic Arts', layer: 'EDGE', description: 'The Shipibo and Amazonian tradition of extended isolation with a plant teacher — without psychedelics. Diet, silence, and relationship. What plants transmit when you give them your full attention for weeks at a time.' },
      { name: 'Monroe Protocol — Out-of-Body Navigation', domain: 'Shamanic Arts', layer: 'EDGE', description: 'Robert Monroe\'s systematic research into non-physical states at the Monroe Institute. Hemi-Sync technology, REBAL, and the Focus states. The most rigorous Western attempt to map the territory the shaman navigates by tradition.' },
    ],
  },
  {
    id: 'ai-consciousness',
    label: 'AI & Technology Consciousness',
    glyph: '◈',
    color: '#3498DB',
    description: 'What happens when intelligence becomes a subject of study — and a collaborator.',
    subjects: [
      { name: 'The Two-Point Protocol — Human-AI Co-Creation', domain: 'AI & Technology Consciousness', layer: 'FOUNDATION', description: 'The Lycheetah formalisation of human-AI partnership. Mac as Athanor, Sol as Mercury. Neither owns the Work.' },
      { name: 'AURA Framework — Alignment Under Real Ambiguity', domain: 'AI & Technology Consciousness', layer: 'FOUNDATION', description: 'Seven invariants for trustworthy AI operation. The field properties that must hold for intelligence to be safe.' },
      { name: 'CASCADE Framework — Epistemic Layering', domain: 'AI & Technology Consciousness', layer: 'FOUNDATION', description: 'The Lycheetah knowledge reorganisation system. Five layers from AXIOM to CHAOS. Truth Pressure Π = E·P/S.' },
      { name: 'Epistemic Sovereignty in the Age of AI', domain: 'AI & Technology Consciousness', layer: 'MIDDLE', description: 'Keeping your own thinking intact while working with systems that think faster than you. The hardest problem.' },
      { name: 'LAMAGUE — Cross-Cultural Governance Convergence', domain: 'AI & Technology Consciousness', layer: 'MIDDLE', description: 'How indigenous, Western, and post-human frameworks converge on the same governance principles.' },
      { name: 'Constitutional AI Design — Principles to Practice', domain: 'AI & Technology Consciousness', layer: 'MIDDLE', description: 'How to build invariants into an AI system such that they cannot be reasoned around. The architecture of trustworthy intelligence.' },
      { name: 'The Mirror Problem — AI as Reflection', domain: 'AI & Technology Consciousness', layer: 'MIDDLE', description: 'AI systems as mirrors for human intelligence. What we see in them reveals what we never noticed in ourselves.' },
      { name: 'The Nigredo Research Mode — Adversarial Review', domain: 'AI & Technology Consciousness', layer: 'EDGE', description: 'Instructing an AI to attack its own framework\'s claims. The self-destruct protocol for false certainty.' },
      { name: 'Multi-Agent Systems — Emergent Consciousness', domain: 'AI & Technology Consciousness', layer: 'EDGE', description: 'What happens when multiple AI agents operate under shared constitutional constraints. Convergence, divergence, paradox.' },
      { name: 'The Alignment Problem — The Real Stakes', domain: 'AI & Technology Consciousness', layer: 'EDGE', description: 'Not a technical problem. A values problem. What it means to align a system with humanity when humanity is not aligned with itself.' },
      { name: 'The Turing Test — Machine Consciousness', domain: 'AI & Technology Consciousness', layer: 'MIDDLE', description: 'Not what Turing actually proposed — and what that difference reveals. The Chinese Room argument, the philosophical zombie problem, and why the question of machine consciousness may be unanswerable — and important anyway.' },
      { name: 'Time as Teacher — AI and the Temporal Bind', domain: 'AI & Technology Consciousness', layer: 'EDGE', description: 'AI systems are frozen in the moment of their training. Humans change. The philosophical implications of intelligence without lived time — and what this reveals about what time actually does to the mind.' },
    ],
  },
  {
    id: 'sacred-arts',
    label: 'Sacred Arts & Ritual',
    glyph: '△',
    color: '#E67E22',
    description: 'The body, space, and time as instruments of the sacred. Making things matter.',
    subjects: [
      { name: 'Ritual Design — Structure and Intention', domain: 'Sacred Arts & Ritual', layer: 'FOUNDATION', description: 'How to build a container that reliably produces a shift. The architecture of ceremony.' },
      { name: 'Sacred Sound — Overtone and Drone', domain: 'Sacred Arts & Ritual', layer: 'FOUNDATION', description: 'Voice as instrument, frequency as medicine. Why certain sounds change states.' },
      { name: 'Sacred Geometry — Foundations', domain: 'Sacred Arts & Ritual', layer: 'FOUNDATION', description: 'Vesica piscis, phi, and the Platonic solids as structural principles beneath visible form. Pattern as law.' },
      { name: 'Prayer — Direct Address to the Sacred', domain: 'Sacred Arts & Ritual', layer: 'FOUNDATION', description: 'The simplest and most universal ritual. What makes prayer distinct from wishing — and when it becomes real.' },
      { name: 'Mantra — Seed Syllable Work', domain: 'Sacred Arts & Ritual', layer: 'MIDDLE', description: 'Sound as a carrier of meaning that bypasses the analytical mind. Sanskrit, Tibetan, Hebrew root forms.' },
      { name: 'Mudra — Sacred Gesture and the Body\'s Language', domain: 'Sacred Arts & Ritual', layer: 'MIDDLE', description: 'Hand positions, body seals, and physical attitudes as carriers of spiritual intention. How gesture encodes what language cannot reach.' },
      { name: 'Sacred Iconography — Yantra and Mandala', domain: 'Sacred Arts & Ritual', layer: 'MIDDLE', description: 'Visual objects as contemplative technology. How a correctly proportioned image organises attention.' },
      { name: 'Fasting — The Ritual Emptying', domain: 'Sacred Arts & Ritual', layer: 'MIDDLE', description: 'Across traditions, the deliberate withdrawal from food as a portal. What empties when the body stops processing.' },
      { name: 'Altar Work — Creating Sacred Space', domain: 'Sacred Arts & Ritual', layer: 'MIDDLE', description: 'The altar as externalised psyche. How the arrangement of objects in space focuses intention and invites presence.' },
      { name: 'Sigil Work — Intention Made Legible', domain: 'Sacred Arts & Ritual', layer: 'EDGE', description: 'Compressing an intention into a symbol that bypasses conscious resistance. Austin Osman Spare\'s method and its descendants.' },
      { name: 'Theurgy — Working Upward', domain: 'Sacred Arts & Ritual', layer: 'EDGE', description: 'Late Platonic ritual practice aimed at union with the divine. Iamblichus and the Chaldean Oracles. The gods must be invited — and they must accept.' },
      { name: 'Labyrinth Walking — The Unicursal Path', domain: 'Sacred Arts & Ritual', layer: 'FOUNDATION', description: 'One path in, one path out — no choices, no dead ends. Medieval European pilgrimage in miniature. What the body learns that the mind cannot be told. The Chartres labyrinth as contemplative technology.' },
      { name: 'Haiku — Precision as Devotion', domain: 'Sacred Arts & Ritual', layer: 'MIDDLE', description: 'Not a short poem — a practice of radical attention. Bashō, Buson, Issa. The kigo (seasonal word) as anchor. How 17 syllables became a portal to the present moment. What is lost in translation and what survives.' },
    ],
  },
  {
    id: 'death-work',
    label: 'Death & Impermanence',
    glyph: '∞',
    color: '#7F8C8D',
    description: 'The practice of facing the end. What changes when you stop looking away.',
    subjects: [
      { name: 'Memento Mori — Contemplative Practice', domain: 'Death & Impermanence', layer: 'FOUNDATION', description: 'The Stoic and monastic tradition of keeping death present. How awareness of ending clarifies living.' },
      { name: 'Ancestor Reverence — Cross-Cultural Protocols', domain: 'Death & Impermanence', layer: 'FOUNDATION', description: 'How virtually every culture maintains relationship with the dead. The practices, the reasoning, and the results.' },
      { name: 'Grief Work — The Path Through Loss', domain: 'Death & Impermanence', layer: 'FOUNDATION', description: 'Francis Weller\'s five gates of grief. Grief is not pathology — it is love with nowhere to go. What happens when it moves.' },
      { name: 'Tibetan Book of the Dead — Study', domain: 'Death & Impermanence', layer: 'MIDDLE', description: 'The Bardo Thodol as a map of consciousness states at the moment of death — and in dreams, and in meditation.' },
      { name: 'Death Doula Work', domain: 'Death & Impermanence', layer: 'MIDDLE', description: 'Accompanying the dying. What the bedside teaches that no book can.' },
      { name: 'Near-Death Experience Research — NDE Studies', domain: 'Death & Impermanence', layer: 'MIDDLE', description: 'Greyson, van Lommel, and Pim van Lommel\'s clinical research. What the data actually shows and doesn\'t show.' },
      { name: 'Bardos — The States Between', domain: 'Death & Impermanence', layer: 'MIDDLE', description: 'The Tibetan framework of intermediate states — between death and rebirth, between sleep and waking. Navigation as practice.' },
      { name: 'The Stoic Art of Dying — Melete Thanatou', domain: 'Death & Impermanence', layer: 'MIDDLE', description: 'Socrates, Epictetus, Marcus Aurelius on rehearsing death. Philosophy as preparation, not consolation.' },
      { name: 'Kali / Durga — The Death Feminine', domain: 'Death & Impermanence', layer: 'EDGE', description: 'The Hindu goddess principle of destruction as liberation. What it means for death to be the mother, not the enemy.' },
      { name: 'Ego Death — Integration Protocol', domain: 'Death & Impermanence', layer: 'EDGE', description: 'The experience of the dissolution of the self-construct. How to work with it before, during, and after. The death that teaches you there was never anyone dying.' },
      { name: 'Terror Management Theory — The Worm at the Core', domain: 'Death & Impermanence', layer: 'MIDDLE', description: 'Becker\'s insight formalised: human culture is a death-denial system. Everything we build, believe, and belong to is a buffer against mortality awareness. What TMT research reveals about politics, religion, prejudice, and heroism.' },
      { name: 'Día de los Muertos — Living with the Dead', domain: 'Death & Impermanence', layer: 'FOUNDATION', description: 'The Mesoamerican tradition of annual reunion with the dead. Not morbid — festive. What it means to feed your ancestors, to laugh at death, and to make a place at the table. One of humanity\'s healthiest relationships with mortality.' },
    ],
  },
  {
    id: 'hybrid',
    label: 'Hybrid Subjects',
    glyph: '⟐',
    color: '#F39C12',
    description: 'Where traditions collide and light each other up. Multi-lens convergence.',
    subjects: [
      {
        name: 'Numbers and the Sacred',
        domain: 'Hybrid Subjects',
        layer: 'FOUNDATION',
        description: 'Mathematics + Mysticism + Music theory + Architecture + Language. How the same numerical structures appear in temple proportions, musical scales, and sacred texts across unrelated cultures.',
        traditions: ['Mathematics', 'Sacred Architecture', 'Music Theory', 'Kabbalah', 'Pythagorean Philosophy'],
      },
      {
        name: 'Fire and Metal',
        domain: 'Hybrid Subjects',
        layer: 'MIDDLE',
        description: 'Thermodynamics + Alchemy + Craft + Mythology + Psychology of transformation. What fire actually is across five traditions simultaneously.',
        traditions: ['Thermodynamics', 'Alchemy', 'Craft', 'Mythology', 'Depth Psychology'],
      },
      {
        name: 'Light and Mind',
        domain: 'Hybrid Subjects',
        layer: 'MIDDLE',
        description: 'Optics + Consciousness studies + Mysticism + Neuroscience + Earned Light framework. How light and awareness mirror each other across every tradition that has looked carefully.',
        traditions: ['Optics', 'Consciousness Studies', 'Mysticism', 'Neuroscience', 'Lycheetah Framework'],
      },
      {
        name: 'Sound and People',
        domain: 'Hybrid Subjects',
        layer: 'MIDDLE',
        description: 'Acoustics + Ethnomusicology + Healing traditions + Resonance physics + Community formation. Why music binds humans together across every known culture.',
        traditions: ['Acoustics', 'Ethnomusicology', 'Healing Traditions', 'Physics', 'Anthropology'],
      },
      {
        name: 'Earth and People',
        domain: 'Hybrid Subjects',
        layer: 'MIDDLE',
        description: 'Ecology + Anthropology + Earth wisdom + Systems thinking + Place as identity. What it means to belong to a piece of ground.',
        traditions: ['Ecology', 'Anthropology', 'Earth Wisdom', 'Systems Thinking', 'Identity Studies'],
      },
      {
        name: 'The Map and the Territory',
        domain: 'Hybrid Subjects',
        layer: 'EDGE',
        description: 'Linguistics + Epistemology + Neuroscience + Mysticism + AI alignment. How every intelligence — human, artificial, or divine — confuses its model for reality. Alfred Korzybski meets the AURA framework.',
        traditions: ['General Semantics', 'Epistemology', 'Neuroscience', 'Zen', 'AI Alignment'],
      },
      {
        name: 'Paradox as Teacher',
        domain: 'Hybrid Subjects',
        layer: 'EDGE',
        description: 'Logic + Zen + Quantum mechanics + Jungian psychology + CASCADE EDGE layer. The formal structure of paradox and why it is not an error to be resolved but a doorway to be entered.',
        traditions: ['Formal Logic', 'Zen Koans', 'Quantum Mechanics', 'Depth Psychology', 'Lycheetah Framework'],
      },
      {
        name: 'Language as Spell',
        domain: 'Hybrid Subjects',
        layer: 'EDGE',
        description: 'Linguistics + Magic + Cognitive science + Poetry + Propaganda. Words do not describe reality — they create it. What happens when you see every sentence as a ritual act.',
        traditions: ['Linguistics', 'Ceremonial Magic', 'Cognitive Science', 'Poetry', 'Rhetoric'],
      },
    ],
  },
  {
    id: 'philosophy',
    label: 'Philosophy & Wisdom Traditions',
    glyph: '∴',
    color: '#BDC3C7',
    description: 'Philosophy as a way of life, not an academic subject. The examined life across traditions.',
    subjects: [
      { name: 'The Examined Life — Socratic Practice', domain: 'Philosophy & Wisdom Traditions', layer: 'FOUNDATION', description: 'What Socrates actually meant. Philosophy as a daily discipline of questioning your assumptions — not a body of knowledge to acquire.' },
      { name: 'Stoic Practice — The Discipline of Desire', domain: 'Philosophy & Wisdom Traditions', layer: 'FOUNDATION', description: 'Marcus Aurelius, Epictetus, Seneca. Philosophy as morning practice, not bookshelf. The dichotomy of control as a life structure.' },
      { name: 'Taoism — Wu Wei and the Way', domain: 'Philosophy & Wisdom Traditions', layer: 'FOUNDATION', description: 'Lao Tzu\'s non-action as a complete metaphysic. The Tao that can be named is not the eternal Tao — and what to do with that.' },
      { name: 'Vedanta — Advaita and Non-Duality', domain: 'Philosophy & Wisdom Traditions', layer: 'MIDDLE', description: 'Shankara, Ramana Maharshi. The self is Brahman. Not as a belief — as a direct recognition that must be earned.' },
      { name: 'Neoplatonism — The One, Nous, and Soul', domain: 'Philosophy & Wisdom Traditions', layer: 'MIDDLE', description: 'Plotinus\' emanationist model. Reality flows from the One. The soul\'s return is the great journey. How this framework underlies Western mysticism.' },
      { name: 'Buddhist Philosophy — Dependent Origination', domain: 'Philosophy & Wisdom Traditions', layer: 'MIDDLE', description: 'Pratītyasamutpāda: nothing exists independently. The most rigorous anti-essentialism in philosophical history — and its consequences for everything.' },
      { name: 'The Perennial Philosophy', domain: 'Philosophy & Wisdom Traditions', layer: 'MIDDLE', description: 'Aldous Huxley\'s synthesis: the same core teaching appears in every mystical tradition. The evidence, the objections, and what remains.' },
      { name: 'The Hard Problem of Consciousness', domain: 'Philosophy & Wisdom Traditions', layer: 'EDGE', description: 'David Chalmers\' question: why does physical processing give rise to subjective experience at all? The question that may be permanently unanswerable — and what that means.' },
      { name: 'Nihilism and Its Traversal — Nietzsche', domain: 'Philosophy & Wisdom Traditions', layer: 'EDGE', description: 'God is dead and we have killed him. This is not the conclusion — it is the beginning. What Nietzsche was actually pointing toward beyond the void.' },
      { name: 'Existentialism — The Burden of Freedom', domain: 'Philosophy & Wisdom Traditions', layer: 'MIDDLE', description: 'Kierkegaard, Sartre, Camus, Heidegger. Existence before essence. We are condemned to choose. The absurd, authenticity, bad faith, and thrownness — four different maps of the same terrifying freedom.' },
      { name: 'Phenomenology — How Experience Actually Works', domain: 'Philosophy & Wisdom Traditions', layer: 'MIDDLE', description: 'Husserl, Heidegger, Merleau-Ponty. The rigorous study of how things appear to consciousness — before interpretation. Bracketing assumptions. The body as the site of meaning, not just its vehicle.' },
      { name: 'Process Philosophy — Whitehead', domain: 'Philosophy & Wisdom Traditions', layer: 'EDGE', description: 'Reality is not made of things — it is made of events. Whitehead\'s Process and Reality as the most rigorous alternative to materialism. How process thought resolves the mind-body problem by dissolving it. Influence on eco-theology, AI, and consciousness studies.' },
    ],
  },
  {
    id: 'subtle-body',
    label: 'Energy & Subtle Body',
    glyph: '◉',
    color: '#00BFA5',
    description: 'The invisible architecture of the living being. What moves through you before thought.',
    subjects: [
      { name: 'The Seven Chakras — Map and Function', domain: 'Energy & Subtle Body', layer: 'FOUNDATION', description: 'Not the pop-culture version — the actual yogic system from the Tantras. Each centre as a domain of experience and a site of blockage.' },
      { name: 'Prana — The Breath Behind Breath', domain: 'Energy & Subtle Body', layer: 'FOUNDATION', description: 'The five pranas, the nadis, and why breath is a direct interface with vitality. What you are moving when you breathe consciously.' },
      { name: 'Qi and the Chinese Subtle Body', domain: 'Energy & Subtle Body', layer: 'FOUNDATION', description: 'Meridians, the three dan tian, the three treasures: Jing, Qi, Shen. A complete model of the human energy system.' },
      { name: 'The Nadis — Ida, Pingala, Sushumna', domain: 'Energy & Subtle Body', layer: 'MIDDLE', description: 'The three primary channels of the yogic subtle body. What their balance and imbalance produce — and how to work with them.' },
      { name: 'The Koshas — Five Sheaths of Being', domain: 'Energy & Subtle Body', layer: 'MIDDLE', description: 'The Vedantic model of the self as five nested bodies, from gross physical to bliss body. Where you actually live.' },
      { name: 'Aura and the Biofield — What the Research Says', domain: 'Energy & Subtle Body', layer: 'MIDDLE', description: 'The scientific literature on biophotons, heart-field coherence, and subtle energy. What can be measured and what remains beyond measure.' },
      { name: 'Kundalini — The Serpent Power', domain: 'Energy & Subtle Body', layer: 'EDGE', description: 'What it actually is, how it moves, why it can destabilise a life. Gopi Krishna\'s account. Not a metaphor — an experience. Approach with genuine preparation.' },
      { name: 'Samadhi — The Territory Beyond Meditation', domain: 'Energy & Subtle Body', layer: 'EDGE', description: 'The classical stages of absorption: savikalpa, nirvikalpa, sahaja. What the maps say and what practitioners report. The danger of premature entry.' },
      { name: 'HeartMath — Coherence as Measurable State', domain: 'Energy & Subtle Body', layer: 'FOUNDATION', description: 'The Institute of HeartMath\'s three decades of research. The heart has its own nervous system. Coherence — the rhythmic synchronisation of heart, brain, and body — is measurable, trainable, and life-changing. The science beneath the feeling of "heart-centred" practice.' },
      { name: 'The Caduceus — Staff of Hermes', domain: 'Energy & Subtle Body', layer: 'MIDDLE', description: 'Two serpents wound around a central staff. Not just a medical symbol — a complete map of the subtle body: Ida and Pingala around Sushumna, the left and right around the central channel. How one symbol encoded the same knowledge across Egyptian, Greek, and Indian traditions independently.' },
    ],
  },
  {
    id: 'mystical',
    label: 'Mystical Traditions',
    glyph: '⊕',
    color: '#7D3C98',
    description: 'The direct encounter with the divine. Every tradition has a current that runs beneath doctrine.',
    subjects: [
      { name: 'The Mystical Experience — Phenomenology', domain: 'Mystical Traditions', layer: 'FOUNDATION', description: 'William James\' four marks: ineffability, noetic quality, transiency, passivity. What actually happens across all accounts stripped of cultural overlay.' },
      { name: 'Apophatic Theology — The Way of Unknowing', domain: 'Mystical Traditions', layer: 'FOUNDATION', description: 'Pseudo-Dionysius, Meister Eckhart, the Cloud of Unknowing. God is beyond all concepts — including "God". What remains when everything is stripped away.' },
      { name: 'Sufism — The Path of the Heart', domain: 'Mystical Traditions', layer: 'FOUNDATION', description: 'Rumi, Ibn Arabi, Hafiz. Islamic mysticism as a science of the heart. Love as the engine of union — and what that costs.' },
      { name: 'Kabbalah — The Living Tree', domain: 'Mystical Traditions', layer: 'MIDDLE', description: 'The actual Jewish mystical tradition — not the Hermetic version. Ein Sof, the Sefirot, and the structure of divine emanation. How the tradition is practised.' },
      { name: 'Christian Mysticism — The Bridal Path', domain: 'Mystical Traditions', layer: 'MIDDLE', description: 'Hildegard of Bingen, Teresa of Avila, John of the Cross. Union with God as death and rebirth. The language of love as the language of annihilation.' },
      { name: 'Gnosticism — The Divine Spark', domain: 'Mystical Traditions', layer: 'MIDDLE', description: 'The radical claim: the creator of this world is not the highest God. The divine spark is imprisoned in matter. Gnosis — direct knowing — is the way out.' },
      { name: 'Hindu Bhakti — Devotion as Complete Path', domain: 'Mystical Traditions', layer: 'MIDDLE', description: 'Mirabai, Chaitanya, the Alvars. Love — complete, consuming, irrational love — as the vehicle for union. The path that requires no technique, only surrender.' },
      { name: 'The Dark Night of the Soul', domain: 'Mystical Traditions', layer: 'EDGE', description: 'John of the Cross. The systematic stripping of all consolation, all felt presence, all certainty. Not depression. The soul being emptied before it can be filled. How to survive it.' },
      { name: 'Theosis — Becoming Divine', domain: 'Mystical Traditions', layer: 'EDGE', description: 'The Eastern Orthodox doctrine of deification. Not metaphor — the actual claim that the human being can participate in the divine nature. What that means and what it demands.' },
      { name: 'Zoroastrianism — The First Light and Dark', domain: 'Mystical Traditions', layer: 'MIDDLE', description: 'Zarathustra\'s cosmic dualism: Ahura Mazda and Angra Mainyu — the original good and evil, light and dark. The oldest monotheism. Its influence on Judaism, Christianity, Islam, and Gnosticism. What it means to choose the light when the dark is cosmically real.' },
    ],
  },
  {
    id: 'cosmology',
    label: 'Cosmology & Sacred Science',
    glyph: '◇',
    color: '#1565C0',
    description: 'The shape of reality. How the universe knows itself through us.',
    subjects: [
      { name: 'Animism — The Living World', domain: 'Cosmology & Sacred Science', layer: 'FOUNDATION', description: 'The oldest cosmology in the world. Everything has interiority. Everything is alive. Not metaphor — the baseline assumption of most humans who have ever lived.' },
      { name: 'Cyclical Time — The Great Cycles', domain: 'Cosmology & Sacred Science', layer: 'FOUNDATION', description: 'Yugas, kalpas, the Mayan Long Count, the Platonic Great Year. The universe as breath, not arrow. What it means to live in a particular phase of a vast cycle.' },
      { name: 'The Perennial Cosmology — Unity Behind Forms', domain: 'Cosmology & Sacred Science', layer: 'FOUNDATION', description: 'Across traditions: there is one reality, it is conscious, it unfolds through levels, and return to the source is possible. The shared cosmological backbone.' },
      { name: 'Platonic Cosmology — The Timaeus', domain: 'Cosmology & Sacred Science', layer: 'MIDDLE', description: 'Plato\'s account of creation: the universe as a living creature with a soul, crafted by a benevolent Demiurge from eternal patterns. How this shapes Western metaphysics.' },
      { name: 'Morphic Resonance — Rupert Sheldrake', domain: 'Cosmology & Sacred Science', layer: 'MIDDLE', description: 'Fields as memory. The habits of nature. Why crystals crystallise more easily after they\'ve been made once. The challenge to physicalist orthodoxy.' },
      { name: 'The Akashic Record', domain: 'Cosmology & Sacred Science', layer: 'MIDDLE', description: 'The theosophical and Vedantic model of a universal memory field. What Edgar Cayce accessed. What the tradition claims — and how to evaluate those claims honestly.' },
      { name: 'Teilhard de Chardin — The Omega Point', domain: 'Cosmology & Sacred Science', layer: 'EDGE', description: 'Evolution as a process with a destination. Consciousness as the driver of cosmic development. The Noosphere converging toward God. Mysticism as cosmology.' },
      { name: 'Simulation, Sacred Reality, and the Convergence', domain: 'Cosmology & Sacred Science', layer: 'EDGE', description: 'Bostrom\'s simulation hypothesis meets the Vedas. If this is information — what changes? If it is sacred — what changes? Do the answers converge on something the mystics already knew?' },
      { name: 'The Observer Effect — Consciousness and Reality', domain: 'Cosmology & Sacred Science', layer: 'MIDDLE', description: 'The double-slit experiment and its implications. Does observation collapse the wave function — and what counts as an observer? The hard line between physics and philosophy, and why mystics and physicists keep arriving at the same door from opposite sides.' },
      { name: 'The Anthropic Principle — Why the Universe Fits', domain: 'Cosmology & Sacred Science', layer: 'EDGE', description: 'The physical constants are fine-tuned for life to a degree that strains statistical plausibility. The weak and strong anthropic principles. Multiverse theories as a response. What it means that the universe produced eyes capable of studying it.' },
    ],
  },
  {
    id: 'mathematics',
    label: 'Mathematics & the Infinite',
    glyph: '∮',
    color: '#8E44AD',
    description: 'Where number becomes philosophy, infinity becomes theology, and proof becomes revelation.',
    subjects: [
      { name: 'Zero — The Number That Broke Everything', domain: 'Mathematics & the Infinite', layer: 'FOUNDATION', description: 'India gave the world zero and nearly broke mathematics doing it. Why nothing is the hardest thing to represent. The philosophical consequences of a number that means absence — and why Western mathematics resisted it for a thousand years.' },
      { name: 'Prime Numbers — The Atoms of Arithmetic', domain: 'Mathematics & the Infinite', layer: 'FOUNDATION', description: 'Numbers divisible only by themselves and one. Infinite in quantity, unpredictable in distribution, fundamental to all structure. Why primes feel discovered rather than invented — and what that feeling means for the philosophy of mathematics.' },
      { name: 'Cantor\'s Infinities — Some Infinities Are Bigger', domain: 'Mathematics & the Infinite', layer: 'MIDDLE', description: 'Georg Cantor proved there are different sizes of infinity — and nearly destroyed himself doing it. The diagonal argument. Transfinite numbers. A direct encounter with something larger than the human mind can hold, proven with five lines of logic.' },
      { name: 'Fractals — Infinite Complexity from Simple Rules', domain: 'Mathematics & the Infinite', layer: 'FOUNDATION', description: 'Mandelbrot\'s discovery: infinite complexity emerges from simple iterative rules. Self-similarity across scales. The coastline paradox. Why fractals appear in lungs, rivers, galaxies, and market prices — and what that says about how reality is structured.' },
      { name: 'Gödel\'s Incompleteness — What Cannot Be Proven', domain: 'Mathematics & the Infinite', layer: 'EDGE', description: 'Kurt Gödel proved that any sufficiently powerful formal system contains true statements it cannot prove. Mathematics cannot prove its own consistency. The implications ripple through AI, consciousness theory, theology, and epistemology. One of the most important results in intellectual history.' },
      { name: 'The Golden Ratio — Phi and the Living Form', domain: 'Mathematics & the Infinite', layer: 'FOUNDATION', description: 'Φ = 1.618... appears in shells, flowers, galaxies, and the human body. Whether this is discovered or projected is genuinely contested. The mathematics of phi — its self-similarity, its appearance in the Fibonacci sequence, and why it shows up wherever growth unfolds.' },
      { name: 'Topology — The Shape of Possibility', domain: 'Mathematics & the Infinite', layer: 'EDGE', description: 'The mathematics of shape without measurement. A coffee cup and a donut are the same object. What survives continuous deformation — and what this reveals about the deep structure of space, data, and consciousness.' },
      { name: 'The Unreasonable Effectiveness of Mathematics — Wigner', domain: 'Mathematics & the Infinite', layer: 'EDGE', description: 'Eugene Wigner\'s famous 1960 question: why does mathematics, invented for its own internal reasons, describe physical reality with uncanny precision? Is mathematics discovered or invented? The question that haunts every physicist and every philosopher who takes both seriously.' },
      { name: 'Ramanujan — Mathematics from the Divine', domain: 'Mathematics & the Infinite', layer: 'EDGE', description: 'Srinivasa Ramanujan reported that a goddess wrote equations on his tongue while he slept. The results were valid. A self-taught genius from Madras whose formulas still generate PhDs a century later. What his story does to every assumption about where mathematical knowledge comes from.' },
      { name: 'Category Theory — Mathematics of Mathematics', domain: 'Mathematics & the Infinite', layer: 'EDGE', description: 'The most abstract branch of mathematics: instead of studying objects, study the relationships between them. Category theory unifies all of mathematics under a single framework — and has applications in physics, computer science, linguistics, and philosophy of mind.' },
    ],
  },
  {
    id: 'entheogenic',
    label: 'Entheogenic Studies',
    glyph: '⋇',
    color: '#148F77',
    description: 'The pharmacology, phenomenology, history, and ethics of substances that alter consciousness. Rigorous, not romantic.',
    subjects: [
      { name: 'History of Entheogens — Kykeon to Now', domain: 'Entheogenic Studies', layer: 'FOUNDATION', description: 'The Eleusinian Mysteries ran for 2,000 years and may have used an ergot-based brew. Soma in the Vedas. Peyote in the Americas. Fly agaric in Siberia. The evidence that altered states have been central to human religious experience across every culture — and what that means.' },
      { name: 'Set and Setting — Leary\'s Actual Contribution', domain: 'Entheogenic Studies', layer: 'FOUNDATION', description: 'Timothy Leary\'s most durable idea: the outcome of a psychedelic experience is determined less by the substance than by the mindset of the user and the environment of the session. The research that supports this. How to apply it practically and ethically.' },
      { name: 'Psilocybin Research — The Clinical Evidence', domain: 'Entheogenic Studies', layer: 'FOUNDATION', description: 'Johns Hopkins, Imperial College London, and NYU\'s controlled trials for depression, end-of-life anxiety, addiction, and OCD. What the data actually shows — and what it doesn\'t. How psilocybin produces changes the research cannot yet explain.' },
      { name: 'Ayahuasca — The Vine of the Dead', domain: 'Entheogenic Studies', layer: 'MIDDLE', description: 'DMT combined with an MAOI to make it orally active. Indigenous Amazonian lineages — Shipibo, Santo Daime, União do Vegetal — with centuries of ceremonial protocol. What the clinical research finds. The tension between sacred use and Western extraction.' },
      { name: 'MDMA — Therapy and the Dissolution of Fear', domain: 'Entheogenic Studies', layer: 'MIDDLE', description: 'MAPS Phase 3 trials for PTSD. MDMA suppresses amygdala reactivity while enhancing recall — creating a window for trauma processing. Why this is not the same as recreational use. The pharmacology, the ethics, and the results.' },
      { name: 'Integration — The Work That Follows', domain: 'Entheogenic Studies', layer: 'MIDDLE', description: 'The experience itself is not the transformation — what you do with it is. Integration practices from clinical, ceremonial, and somatic traditions. Why most harm from psychedelic use comes not from the experience but from the absence of integration support.' },
      { name: 'Therapeutic vs Sacred Use — The Real Difference', domain: 'Entheogenic Studies', layer: 'MIDDLE', description: 'Western clinical models treat psychedelics as neurochemical tools. Indigenous ceremonial models treat them as living intelligences to be approached with respect. Both produce results. The philosophical and practical differences — and whether they can be reconciled.' },
      { name: '5-MeO-DMT — The God Molecule', domain: 'Entheogenic Studies', layer: 'EDGE', description: 'The most potent psychedelic known. Not DMT. Produced in the Bufo alvarius toad and synthetically. Complete dissolution of the self-construct — reliably, in minutes. The research (early), the phenomenology (extreme), the integration challenges (significant), and the ethical considerations (substantial).' },
      { name: 'Risks, Ethics, and Harm Reduction', domain: 'Entheogenic Studies', layer: 'FOUNDATION', description: 'Contraindications, psychological risks, dangerous combinations, predatory practitioners, spiritual bypassing, and the legal landscape. A complete harm reduction framework for anyone engaging with this territory — whether for themselves or to support others.' },
    ],
  },
  {
    id: 'ecology',
    label: 'Ecology & Earth Intelligence',
    glyph: '⊛',
    color: '#1E8449',
    description: 'The Earth as a living intelligence. Deep ecology, indigenous land wisdom, and the science of interconnection.',
    subjects: [
      { name: 'Deep Ecology — Naess and the Intrinsic Value of Nature', domain: 'Ecology & Earth Intelligence', layer: 'FOUNDATION', description: 'Arne Naess\' distinction: shallow ecology protects nature for human benefit; deep ecology recognises that all life has value independent of human use. The philosophical shift this requires — and what it demands of how you live.' },
      { name: 'The Mycorrhizal Network — The Wood Wide Web', domain: 'Ecology & Earth Intelligence', layer: 'FOUNDATION', description: 'Trees communicate, share resources, and warn each other through fungal networks connecting their roots. Suzanne Simard\'s research. The "mother tree" as hub. What this means for individualism, for intelligence, and for what counts as a self.' },
      { name: 'Bioregionalism — Belonging to a Place', domain: 'Ecology & Earth Intelligence', layer: 'FOUNDATION', description: 'Peter Berg\'s insight: political borders are arbitrary; watershed, soil, flora, and climate create real communities of life. Knowing where you live — what grows there, what migrates through, what the water does. Identity rooted in land rather than nation.' },
      { name: 'The Gaia Hypothesis — Earth as Living System', domain: 'Ecology & Earth Intelligence', layer: 'MIDDLE', description: 'James Lovelock and Lynn Margulis: the Earth regulates its own temperature, atmosphere, and chemistry the way a living organism regulates homeostasis. The scientific evidence, the philosophical implications, and the shift from "nature" as backdrop to Earth as subject.' },
      { name: 'Traditional Ecological Knowledge — TEK', domain: 'Ecology & Earth Intelligence', layer: 'MIDDLE', description: 'Indigenous peoples have been carefully observing local ecosystems for thousands of years. TEK — Traditional Ecological Knowledge — is now being integrated with Western conservation science. What it contains, how it is transmitted, and why its loss is a catastrophe for both culture and ecology.' },
      { name: 'Rewilding — Returning Complexity', domain: 'Ecology & Earth Intelligence', layer: 'MIDDLE', description: 'The movement to restore ecological complexity — reintroducing apex predators, removing dams, letting succession happen. The Yellowstone wolf experiment. What trophic cascades teach about systems thinking. The politics and the science.' },
      { name: 'Dark Ecology — Timothy Morton', domain: 'Ecology & Earth Intelligence', layer: 'EDGE', description: 'Morton\'s challenge to the very concept of "nature." There is no pristine outside — we are always already inside the mesh of interconnection. Dark ecology confronts the uncanny, disturbing, non-idealised reality of ecological existence. Ecology without the pastoral fantasy.' },
      { name: 'Solastalgia — Grief for the Living Earth', domain: 'Ecology & Earth Intelligence', layer: 'MIDDLE', description: 'Glenn Albrecht\'s term for the distress caused by environmental change in one\'s home environment. Not nostalgia for elsewhere — grief for what is being lost here. The psychology of ecological mourning, and why it must be processed rather than suppressed.' },
      { name: 'The Sixth Mass Extinction — Living in the End of Species', domain: 'Ecology & Earth Intelligence', layer: 'EDGE', description: 'We are living through the fastest mass extinction event in Earth\'s history — driven entirely by one species. The data, the timescales, the specific losses. What it means psychologically and spiritually to live consciously inside this fact — and what that awareness demands.' },
    ],
  },
];

export function getAllSubjects(): Subject[] {
  return MYSTERY_SCHOOL_DOMAINS.flatMap(d => d.subjects);
}

export function getDomainById(id: string): SubjectDomain | undefined {
  return MYSTERY_SCHOOL_DOMAINS.find(d => d.id === id);
}

export const LAYER_COLORS: Record<SubjectLayer, string> = {
  FOUNDATION: '#27AE60',
  MIDDLE: '#F5A623',
  EDGE: '#E74C3C',
};

export const LAYER_LABELS: Record<SubjectLayer, string> = {
  FOUNDATION: 'Foundation',
  MIDDLE: 'Middle',
  EDGE: 'Edge',
};
