// AETHERA image array — positional mapping to AETHERA_DECK order.
// 92 files (2 variant/extras). AETHERA_DECK has 90 cards.
// ORDER UNVERIFIED — phone-test to confirm art matches card names.
import { AETHERA_DECK } from './aethera';

const AETHERA_ART: any[] = [
  require('../../assets/aethera/0EQ81.jpg'),
  require('../../assets/aethera/2MbyO.jpg'),
  require('../../assets/aethera/2U79t.jpg'),
  require('../../assets/aethera/3Cc34.jpg'),
  require('../../assets/aethera/3GIro.jpg'),
  require('../../assets/aethera/4ORjH.jpg'),
  require('../../assets/aethera/4vjWS.jpg'),
  require('../../assets/aethera/4YN1H.jpg'),
  require('../../assets/aethera/5gpie.jpg'),
  require('../../assets/aethera/5Sez9.jpg'),
  require('../../assets/aethera/5U9T0.jpg'),
  require('../../assets/aethera/6lTa8.jpg'),
  require('../../assets/aethera/6UU2U.jpg'),
  require('../../assets/aethera/7jj5O.jpg'),
  require('../../assets/aethera/95PpX.jpg'),
  require('../../assets/aethera/9jEBm.jpg'),
  require('../../assets/aethera/aGbIZ.jpg'),
  require('../../assets/aethera/aToU7.jpg'),
  require('../../assets/aethera/b4rU6.jpg'),
  require('../../assets/aethera/bkjnM.jpg'),
  require('../../assets/aethera/byQBi.jpg'),
  require('../../assets/aethera/c3XWu.jpg'),
  require('../../assets/aethera/cDLl1.jpg'),
  require('../../assets/aethera/DzaKe.jpg'),
  require('../../assets/aethera/EFXS4.jpg'),
  require('../../assets/aethera/ePaZJ.jpg'),
  require('../../assets/aethera/EQbYw.jpg'),
  require('../../assets/aethera/EurTO.jpg'),
  require('../../assets/aethera/F8tti.jpg'),
  require('../../assets/aethera/FmPn3.jpg'),
  require('../../assets/aethera/fndnS.jpg'),
  require('../../assets/aethera/fP0hj.jpg'),
  require('../../assets/aethera/G9TTD.jpg'),
  require('../../assets/aethera/gJBJ5.jpg'),
  require('../../assets/aethera/gOftR.jpg'),
  require('../../assets/aethera/gQIWF.jpg'),
  require('../../assets/aethera/GTZsZ.jpg'),
  require('../../assets/aethera/GxFS1.jpg'),
  require('../../assets/aethera/HCjmE.jpg'),
  require('../../assets/aethera/hcUEw.jpg'),
  require('../../assets/aethera/Hjwdi.jpg'),
  require('../../assets/aethera/hk3Ny.jpg'),
  require('../../assets/aethera/HWcpj.jpg'),
  require('../../assets/aethera/icQbC.jpg'),
  require('../../assets/aethera/IDhAG.jpg'),
  require('../../assets/aethera/io7yb.jpg'),
  require('../../assets/aethera/iuS9l.jpg'),
  require('../../assets/aethera/IxoFj.jpg'),
  require('../../assets/aethera/iyrfF.jpg'),
  require('../../assets/aethera/jgwu6.jpg'),
  require('../../assets/aethera/jprsC.jpg'),
  require('../../assets/aethera/KNYlx.jpg'),
  require('../../assets/aethera/KqxNI.jpg'),
  require('../../assets/aethera/lIBcS.jpg'),
  require('../../assets/aethera/LVxHm.jpg'),
  require('../../assets/aethera/LYGhN.jpg'),
  require('../../assets/aethera/m4Ton.jpg'),
  require('../../assets/aethera/New7D.jpg'),
  require('../../assets/aethera/nQWAF.jpg'),
  require('../../assets/aethera/ny4wR.jpg'),
  require('../../assets/aethera/O5bSy.jpg'),
  require('../../assets/aethera/O5mXO.jpg'),
  require('../../assets/aethera/OgSQz.jpg'),
  require('../../assets/aethera/OqRUY.jpg'),
  require('../../assets/aethera/OzbNB.jpg'),
  require('../../assets/aethera/PeYnp.jpg'),
  require('../../assets/aethera/qqNnn.jpg'),
  require('../../assets/aethera/r4RZX.jpg'),
  require('../../assets/aethera/r5BG6.jpg'),
  require('../../assets/aethera/RIlJi.jpg'),
  require('../../assets/aethera/rpStf.jpg'),
  require('../../assets/aethera/sNAWp.jpg'),
  require('../../assets/aethera/SQ3k7.jpg'),
  require('../../assets/aethera/T1xuZ.jpg'),
  require('../../assets/aethera/tliQz.jpg'),
  require('../../assets/aethera/ucYQj.jpg'),
  require('../../assets/aethera/UnIeQ.jpg'),
  require('../../assets/aethera/uUB1x.jpg'),
  require('../../assets/aethera/uYSAz.jpg'),
  require('../../assets/aethera/vGRlc.jpg'),
  require('../../assets/aethera/ViNuF.jpg'),
  require('../../assets/aethera/Vlfx4.jpg'),
  require('../../assets/aethera/vlQSV.jpg'),
  require('../../assets/aethera/vQOXx.jpg'),
  require('../../assets/aethera/x5l0J.jpg'),
  require('../../assets/aethera/xbe2k.jpg'),
  require('../../assets/aethera/xrEQ6.jpg'),
  require('../../assets/aethera/xVQFN.jpg'),
  require('../../assets/aethera/yuKeN.jpg'),
  require('../../assets/aethera/zRjWC.jpg'),
  require('../../assets/aethera/ZZ2VB.jpg'),
];

// Map card id → image (positional: AETHERA_DECK[i] → AETHERA_ART[i])
export const AETHERA_IMAGE: Record<string, any> = Object.fromEntries(
  AETHERA_DECK.map((card, i) => [card.id, AETHERA_ART[i] ?? AETHERA_ART[0]])
);
