// ─── LYCHEETAH CUSTOM TAROT DECK ─────────────────────────────────────────────
// Drop art into assets/tarot/ with the exact filenames listed below.
// .jpg = real Lycheetah art landed  |  .png = placeholder card back (still incoming)
// Missing 12: Strength, Hermit, Wheel of Fortune, Justice, Hanged Man, Death,
//             Temperance, Devil + Ace/Two/Three/Four of Pentacles (source pages 2,4,9)

export const CARD_IMAGE: Record<string, ReturnType<typeof require> | null> = {
  // ── Major Arcana ──
  'The Fool':           require('../../assets/tarot/the_fool.jpg'),
  'The Magician':       require('../../assets/tarot/the_magician.jpg'),
  'The High Priestess': require('../../assets/tarot/the_high_priestess.jpg'),
  'The Empress':        require('../../assets/tarot/the_empress.jpg'),
  'The Emperor':        require('../../assets/tarot/the_emperor.jpg'),
  'The Hierophant':     require('../../assets/tarot/the_hierophant.jpg'),
  'The Lovers':         require('../../assets/tarot/the_lovers.jpg'),
  'The Chariot':        require('../../assets/tarot/the_chariot.jpg'),
  'Strength':           require('../../assets/tarot/strength.png'),
  'The Hermit':         require('../../assets/tarot/the_hermit.png'),
  'Wheel of Fortune':   require('../../assets/tarot/wheel_of_fortune.png'),
  'Justice':            require('../../assets/tarot/justice.png'),
  'The Hanged Man':     require('../../assets/tarot/the_hanged_man.png'),
  'Death':              require('../../assets/tarot/death.png'),
  'Temperance':         require('../../assets/tarot/temperance.png'),
  'The Devil':          require('../../assets/tarot/the_devil.png'),
  'The Tower':          require('../../assets/tarot/the_tower.jpg'),
  'The Star':           require('../../assets/tarot/the_star.jpg'),
  'The Moon':           require('../../assets/tarot/the_moon.jpg'),
  'The Sun':            require('../../assets/tarot/the_sun.jpg'),
  'Judgement':          require('../../assets/tarot/judgement.jpg'),
  'The World':          require('../../assets/tarot/the_world.jpg'),
  // ── Wands ──
  'Ace of Wands':       require('../../assets/tarot/ace_of_wands.jpg'),
  'Two of Wands':       require('../../assets/tarot/two_of_wands.jpg'),
  'Three of Wands':     require('../../assets/tarot/three_of_wands.jpg'),
  'Four of Wands':      require('../../assets/tarot/four_of_wands.jpg'),
  'Five of Wands':      require('../../assets/tarot/five_of_wands.jpg'),
  'Six of Wands':       require('../../assets/tarot/six_of_wands.jpg'),
  'Seven of Wands':     require('../../assets/tarot/seven_of_wands.jpg'),
  'Eight of Wands':     require('../../assets/tarot/eight_of_wands.jpg'),
  'Nine of Wands':      require('../../assets/tarot/nine_of_wands.jpg'),
  'Ten of Wands':       require('../../assets/tarot/ten_of_wands.jpg'),
  'Page of Wands':      require('../../assets/tarot/page_of_wands.jpg'),
  'Knight of Wands':    require('../../assets/tarot/knight_of_wands.jpg'),
  'Queen of Wands':     require('../../assets/tarot/queen_of_wands.jpg'),
  'King of Wands':      require('../../assets/tarot/king_of_wands.jpg'),
  // ── Cups ──
  'Ace of Cups':        require('../../assets/tarot/ace_of_cups.jpg'),
  'Two of Cups':        require('../../assets/tarot/two_of_cups.jpg'),
  'Three of Cups':      require('../../assets/tarot/three_of_cups.jpg'),
  'Four of Cups':       require('../../assets/tarot/four_of_cups.jpg'),
  'Five of Cups':       require('../../assets/tarot/five_of_cups.jpg'),
  'Six of Cups':        require('../../assets/tarot/six_of_cups.jpg'),
  'Seven of Cups':      require('../../assets/tarot/seven_of_cups.jpg'),
  'Eight of Cups':      require('../../assets/tarot/eight_of_cups.jpg'),
  'Nine of Cups':       require('../../assets/tarot/nine_of_cups.jpg'),
  'Ten of Cups':        require('../../assets/tarot/ten_of_cups.jpg'),
  'Page of Cups':       require('../../assets/tarot/page_of_cups.jpg'),
  'Knight of Cups':     require('../../assets/tarot/knight_of_cups.jpg'),
  'Queen of Cups':      require('../../assets/tarot/queen_of_cups.jpg'),
  'King of Cups':       require('../../assets/tarot/king_of_cups.jpg'),
  // ── Swords ──
  'Ace of Swords':      require('../../assets/tarot/ace_of_swords.jpg'),
  'Two of Swords':      require('../../assets/tarot/two_of_swords.jpg'),
  'Three of Swords':    require('../../assets/tarot/three_of_swords.jpg'),
  'Four of Swords':     require('../../assets/tarot/four_of_swords.jpg'),
  'Five of Swords':     require('../../assets/tarot/five_of_swords.jpg'),
  'Six of Swords':      require('../../assets/tarot/six_of_swords.jpg'),
  'Seven of Swords':    require('../../assets/tarot/seven_of_swords.jpg'),
  'Eight of Swords':    require('../../assets/tarot/eight_of_swords.jpg'),
  'Nine of Swords':     require('../../assets/tarot/nine_of_swords.jpg'),
  'Ten of Swords':      require('../../assets/tarot/ten_of_swords.jpg'),
  'Page of Swords':     require('../../assets/tarot/page_of_swords.jpg'),
  'Knight of Swords':   require('../../assets/tarot/knight_of_swords.jpg'),
  'Queen of Swords':    require('../../assets/tarot/queen_of_swords.jpg'),
  'King of Swords':     require('../../assets/tarot/king_of_swords.jpg'),
  // ── Pentacles ──
  'Ace of Pentacles':   require('../../assets/tarot/ace_of_pentacles.png'),
  'Two of Pentacles':   require('../../assets/tarot/two_of_pentacles.png'),
  'Three of Pentacles': require('../../assets/tarot/three_of_pentacles.png'),
  'Four of Pentacles':  require('../../assets/tarot/four_of_pentacles.png'),
  'Five of Pentacles':  require('../../assets/tarot/five_of_pentacles.jpg'),
  'Six of Pentacles':   require('../../assets/tarot/six_of_pentacles.jpg'),
  'Seven of Pentacles': require('../../assets/tarot/seven_of_pentacles.jpg'),
  'Eight of Pentacles': require('../../assets/tarot/eight_of_pentacles.jpg'),
  'Nine of Pentacles':  require('../../assets/tarot/nine_of_pentacles.jpg'),
  'Ten of Pentacles':   require('../../assets/tarot/ten_of_pentacles.jpg'),
  'Page of Pentacles':  require('../../assets/tarot/page_of_pentacles.jpg'),
  'Knight of Pentacles':require('../../assets/tarot/knight_of_pentacles.jpg'),
  'Queen of Pentacles': require('../../assets/tarot/queen_of_pentacles.jpg'),
  'King of Pentacles':  require('../../assets/tarot/king_of_pentacles.jpg'),
};
